### PR TITLE
Fix whitelabel name and icon don't work

### LINKED ISSUE #26: The formidable modal block option does not use whitelabel icons.
We should use the same icon as "Formidable Forms".

Screen Shot 2023-08-24 at 11 35 20 AM

### PR DESCRIPTION
**Pull request by truongwp**
Fixes #26

### CODE REVIEW

File: blocks-src/frm-modal/index.js [hunk 1]
```diff
@@ -1,12 +1,13 @@
 import { registerBlockType, unregisterBlockType } from '@wordpress/blocks';
 import { InnerBlocks } from '@wordpress/block-editor';
+import FormidableIcon from '../../../formidable/js/src/common/components/icon';
```
Comment (Crabcyborg) [inline blocks-src/frm-modal/index.js:3]: @truongwp It looks like in Pro we use `import FormidableIcon from 'Formidable/components/icon';`.

Does that work here? The hard coded path could cause issues if someone happened to be using `formidable-beta` or some other folder name.

I'm not sure exactly how the `Formidable/` path is set up but it seems like it could be safer.

Comment (truongwp) [reply blocks-src/frm-modal/index.js:3]: The `Formidable/` path is set up in the webpack config file, which also uses the `formidable` folder name: https://github.com/Strategy11/formidable-pro/blob/master/webpack.config.js#L18

We just need this when building the code. The built file doesn't contain any `@import`s and paths, so it doesn't contain any issues.

If you want to use the same import as in the Pro, I'll add the webpack config file for this addon.

Comment (Crabcyborg) [reply blocks-src/frm-modal/index.js:3]: Thanks for the explanation!

Since the JS file that gets built doesn't use the path it should be fine.
